### ISSUE TITLE
Feature request: custom axis sort order

### ISSUE THREAD

**Issue by karldw** [const-ae/ggupset#10]
Nice project, @const-ae!

As I've been trying it out, I realized it would be nice to have a ggupset plot that allowed me to easily specify the ordering of the x-axis. Currently, it's possible to do this by setting a ggplot `x` aesthetic that has the order I want after alphabetizing, but it's a little clunky because the `x` aesthetic is used for both the upset categories and for ordering the categories.
What do you think?

Here's a demo where, for some reason, the ordering I want is sorted in `mpg`.

```r
library(dplyr)
library(ggplot2)
library(ggupset)
# Need to pad with zeros to get `combined` to sort correctly.
sprintf_pattern <- paste0("%0", nchar(as.character(nrow(mtcars))), "d")

df <- mtcars %>% 
  arrange(mpg) %>%
  mutate(combined =
    paste0(sprintf(sprintf_pattern, row_number()), "_Cyl: ", cyl, "_Gears: ", gear)
  )
# Drop the first split, that is the "01" etc values, then retain the 
# remainder as the desired levels to include
all_levels <- strsplit(df$combined, split="_", fixed=TRUE) %>% simplify2array() 
desired_levels <- all_levels[-1,] %>% as.vector() %>% unique()

plt <- ggplot(df, aes(combined, mpg)) +
  geom_point()+
  axis_combmatrix(sep="_", levels=desired_levels)
plt

```

![demo_plot](https://user-images.githubusercontent.com/12504708/79286443-77899480-7e75-11ea-86dc-cc5b74a2ab1b.png)

**Comment by const-ae** [comment]
Hi Karl,

thank you, I am always happy to hear when people like my project :)

My suggestion to simplify the zero-padding workaround that you develop would be to use `forcats::fct_reorder()`. The function takes a `factor` as input and reorders it according to a second variable, for example `mpg`:

``` r
library(dplyr)
library(ggplot2)
library(ggupset)

df <- mtcars %>% 
  mutate(combined = paste0(seq_len(n()), "_Cyl: ", cyl, "_Gears: ", gear)) %>%
  mutate(combined_fct = forcats::fct_reorder(as.factor(combined), mpg))

# Drop the first split, that is the "01" etc values, then retain the 
# remainder as the desired levels to include
all_levels <- strsplit(df$combined, split="_", fixed=TRUE) %>% simplify2array() 
desired_levels <- all_levels[-1,] %>% as.vector() %>% unique()

ggplot(df, aes(combined_fct, mpg)) +
  geom_point()+
  axis_combmatrix(sep="_", levels = desired_levels)
```

![](https://i.imgur.com/OsQ6b4T.png)

<sup>Created on 2020-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

As you can see, you still have some boilerplate to get the `desired_levels`, but it does simplify the code a bit. For example the `seq_len(n())` in the `paste0()` call is only necessary to make sure that each observation has it's own x-position.

**Comment by karldw** [comment]
Ah, nice. Thanks!
