### ISSUE TITLE
Display totals above bars

### ISSUE THREAD

**Issue by hfshr** [const-ae/ggupset#16]
Hi,  I'm wondering if there is an easy way to add the total counts for each  intersection above its corresponding bar? I've tried a few hacky solutions but they don't look quite right.

**Comment by const-ae** [comment]
Hey, checkout this [post](https://stackoverflow.com/a/26556180/604854). I hope that answers your question.

**Comment by hfshr** [comment]
Ah easy as that. Thanks!
