### ISSUE TITLE
Manual order

### ISSUE THREAD

**Issue by FrederickClasen** [const-ae/ggupset#19]
Hi,

Thanks for the awesome package - was a massive help to me!

Is there a way to manually order instead of by freq or order. In the particular case that I am using it there is a biological reason as to have a very specific order for the different sets.

Cheers,
Frederick

**Comment by const-ae** [comment]
Hi Frederick,

thanks for the kind words :)

Take a look at the https://github.com/const-ae/ggupset#what-if-i-need-more-flexibility section. You can then combine this with factors and explicitly set the order of the levels or use [`forcats::fct_infreq()`](https://forcats.tidyverse.org/reference/fct_inorder.html).

Best,
Constantin

**Comment by FrederickClasen** [comment]
Hi Constantin,

Thanks for the suggestions. 

I tried this and for some reason it is not working. I paste some code below if it might help:

`# p is an object from another package #
# dotplot makes a ggplot object #
q = p
q = dotplot(q)
q$data = na.omit(q$data)
q$data = as.tibble(q$data)
q$data$Cluster = gsub("\n.*","",q$data$Cluster)

# order Cluster column by vector comps #
# Cluster has format experiment1_vs_experiment2 #
q$data$Cluster = q$data$Cluster[order(match(q$data$Cluster,comps))]
q$data$Cluster = fct_inorder(q$data$Cluster)
#q$data$Cluster = factor(q$data$Cluster,levels=unique(q$data$Cluster))

qq = q + aes(x=Cluster)
qq = qq + axis_combmatrix(sep = "_vs_")
qq`

The order of the annotation is still in alphabetical order and not as the factors.

This could be due to the dotplot object but I do not think so.

Any suggestions would be helpful.

Cheers,
Frederick

**Comment by FrederickClasen** [comment]
Hi Constantin,

Thanks for the suggestions.

I tried this and for some reason it is not working. I paste some code below if it might help:

```
# p is an object from another package #
# dotplot makes a ggplot object #
q = p
q = dotplot(q)
q$data = na.omit(q$data)
q$data = as.tibble(q$data)
q$data$Cluster = gsub("\n.*","",q$data$Cluster)

# order Cluster column by vector comps #
# Cluster has format experiment1_vs_experiment2 #
q$data$Cluster = q$data$Cluster[order(match(q$data$Cluster,comps))]
q$data$Cluster = fct_inorder(q$data$Cluster)
#q$data$Cluster = factor(q$data$Cluster,levels=unique(q$data$Cluster))

qq = q + aes(x=Cluster)
qq = qq + axis_combmatrix(sep = "_vs_")
qq

```





The order of the annotation is still in alphabetical order and not as the factors.

This could be due to the dotplot object but I do not think so.

Any suggestions would be helpful.

Cheers,
Frederick

**Comment by const-ae** [comment]
Where does the `dotplot` method come from. Take a look at its source and try to do what it does internally yourself. Otherwise I am afraid, this won't work

**Comment by FrederickClasen** [comment]
Hi Constantin,

Thanks for your help - it is working now. Best to not use objects created from other packages.

Cheers,
Frederick

**Comment by const-ae** [comment]
Great. I am happy to hear that you solved the problem :)
(And yes, sometimes doing things yourself is the solution :D)

**Comment by a14578** [comment]
Hi @const-ae , any idea how I can implement forcats::fct_infreq() into the below code to order intersections please? Would really appreciate your help.

I would like to order the intersections (x axis or gene combinations) in the following order: Gene_A, Gene_B, Gene_D, Gene_E Gene_D with Gene_H, Gene_C with GeneE with Gene_G with Gene_I, Gene_B with Gene_C with Gene_F with Gene_J.


sample <- c("NK_H1_053", "Sample_A", "T7-488", "5567625262", "Sample_A", "50509588", "ABC_AJDH_GH_2002_56789_678", "505312347654633", "5567625262", "Sample_A", "50509588", "505312347654633", "Sample_A", "505312347654633", "5567625262", "50806829", "505312347654633", "5567625262")
Phenotype <- c("low", "high", "low", "high", "high", "high", "high", "high", "high", "high", "high", "high", "high", "high", "high", "high", "high", "high")
Size <- c("23", "6", "24", "6", "6", "6", "15", "6", "6", "6", "6", "6", "6", "6", "6", "16", "6", "6")
Speed <- c("Fast", "Fast", "Slow", "Fast", "Fast", "Fast", "Fast", "Slow", "Fast", "Fast", "Fast", "Slow", "Fast", "Slow", "Fast", "Fast", "Slow", "Fast")
AGDe_mutations <- c("No_AGDe_mutation", "AGDe35", "No_AGDe_mutation", "No_AGDe_mutation", "AGDe35", "AGDe35;AGDe12GD", "No_AGDe_mutation", "AGDe35;AGDe12GD", "No_AGDe_mutation", "AGDe35", "AGDe35;AGDe12GD", "AGDe35;AGDe12GD", "AGDe35", "AGDe35;AGDe12GD", "No_AGDe_mutation", "No_AGDe_mutation", "AGDe35;AGDe12GD", "No_AGDe_mutation")
genes <- c("Gene_A", "Gene_E", "Gene_E", "Gene_F", "Gene_G", "Gene_D", "Gene_D", "Gene_C", "Gene_C", "Gene_C", "Gene_H", "Gene_I", "Gene_I", "Gene_B", "Gene_B", "Gene_B", "Gene_J", "Gene_J")

df <- data.frame(sample, Phenotype, Size, Speed, AGDe_mutations, genes)


df %>%
  group_by(sample, Phenotype, Size) %>% 
  summarize(gene_list = list(genes)) %>%
  ggplot(aes(gene_list, Size)) + geom_violin(width=2.1, alpha=2.5) + geom_jitter(aes(color=Phenotype), width=0.001, height = 0.001) +
  labs(x = "Genes", y = "size") + 
  scale_x_upset(intersections = list(c("Gene_A"), c("Gene_B"), c("Gene_D"), c("Gene_E"), c("Gene_D", "Gene_H"), c("Gene_C", "GeneE", "Gene_G", "Gene_I"), c("Gene_B", "Gene_C", "Gene_F", "Gene_J"), c("Gene_B", "Gene_C", "Gene_I", "Gene_J")),
  sets = c("Gene_A", "Gene_B", "Gene_C", "Gene_D", "Gene_E", "Gene_F", "Gene_G", "Gene_H", "Gene_I", "Gene_J")) +
  theme_combmatrix(combmatrix.panel.line.size = 0.8) +
  geom_hline(yintercept=18, color="pink", size=1, linetype = 'dashed') +
  theme_combmatrix(combmatrix.label.text = element_text(size=12), combmatrix.label.extra_spacing = 5)
