### ISSUE TITLE
dual barplot and y-axis

### ISSUE THREAD

**Issue by lvestito** [const-ae/ggupset#24]
Hi, 

firstly thank you very much for your very useful package. 
If I can I would like to ask some questions that might improve my data visualization: 

- how could I generate a double layer to the barplot (as shown in the figure) that refers to a dual y-axis?
for example, one y-axis shows the count as default and a second y-axis on the other side shows a % or a rate that reflects a bar of different color in the barplot. 

![image](https://user-images.githubusercontent.com/61631773/110547153-731e3800-8127-11eb-8de8-710cff1a8fa8.png)

- how can I specify the ratio between the barplot and the combination matrix?
(I would like for example to give more space to the matrix and having a smaller barplot on top)

Thank you very much for your help

**Comment by const-ae** [comment]
Hi, 

I am not sure I understand the question and to what extend it relates specifically to `ggupset`. 

ggplot2 only allows scaled version for a secondary axis. For more context see this [answer](https://stackoverflow.com/a/3101876/604854) by Hadley Wickham (the author of ggplot).

Maybe you could provide a [reproducible example](https://reprex.tidyverse.org/) that does what you want to achieve with a classical categorical x-axis and then we could see how to achieve the same with `ggupset`.

Best,
Constantin

**Comment by lvestito** [comment]
Hi Constantin, 

thank you very much for your reply and your help.
Sorry, I will provide a reproducible example for it. 

In the meantime, if that's ok I would like to ask you other two questions about the package:

- When using the ggupset default parameters I receive an output similar to the 'distinct' mode in UpsetR 

![image](https://user-images.githubusercontent.com/61631773/110667113-d8266c00-81c1-11eb-93bb-52b42b325b19.png)

but I would actually prefer if the combination sets could overlap like un the the 'intersect' mode in UpsetR
I'm sorry if I missed this in the documentation but Is there any way to achieve that instead?

- another question would be: 
is there a way of exporting the combinations from the combination matrix and their counts as a data frame?

Thank you very much

**Comment by lvestito** [comment]
Hi, 

that worked perfectly, thank you very much for your help.
