### ISSUE TITLE
Can't modify axis.text.y via theme()?

### ISSUE THREAD

**Issue by daranzolin** [const-ae/ggupset#29]
Loving my upset plots!

I wanted to remove the y-axis from my upset plot, but am getting a units error. Reprex below:

``` r
  library(ggplot2)
  library(tidyverse, warn.conflicts = FALSE)
  library(ggupset)
  
  tidy_movies %>%
    distinct(title, year, length, .keep_all=TRUE) %>%
    ggplot(aes(x=Genres)) +
    geom_bar() +
    scale_x_upset(n_intersections = 20) +
    theme(axis.text.y = element_blank())
#> Warning: Removed 100 rows containing non-finite values (stat_count).
#> Error in unit((calc_element("axis.text.y", theme)$size + theme$combmatrix.label.extra_spacing) * : 'x' and 'units' must have length > 0
```
<sup>Created on 2021-11-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

I'm on a slightly older version of R (4.0.3) if that's relevant?

**Comment by const-ae** [comment]
Hi David,

that is indeed a bug. I fixed it in https://github.com/const-ae/ggupset/commit/6a558e90e56139b6f4fa0bfa8d42c55e680c612e.

``` r
tidy_movies %>%
  distinct(title, year, length, .keep_all=TRUE) %>%
  ggplot(aes(x=Genres)) +
  geom_bar() +
  scale_x_upset(n_intersections = 20) +
  theme(axis.text.y = element_blank())
#> Warning: Removed 100 rows containing non-finite values (stat_count).
```

![](https://i.imgur.com/GfAoUG8.png)

The `theme` applies to the main plot and the combination axis. I usually calculate height of the combination axis based on the height of the y-axis labels. However, without the y-axis you can still adjust the height using the `combmatrix.label.extra_spacing` parameter

``` r
# Fix the height using 'combmatrix.label.extra_spacing'
tidy_movies %>%
  distinct(title, year, length, .keep_all=TRUE) %>%
  ggplot(aes(x=Genres)) +
  geom_bar() +
  scale_x_upset(n_intersections = 20) +
  theme(axis.text.y = element_blank(), combmatrix.label.extra_spacing = 30)
#> Warning: Removed 100 rows containing non-finite values (stat_count).
```

![](https://i.imgur.com/BbXgBkL.png)

You can install the latest version directly from github using `devtools::install_github("const-ae/ggupset")`

Best,
Constantin
