### ISSUE TITLE
Plot intersections and aggregation of sets?

### ISSUE THREAD

**Issue by toddknutson** [const-ae/ggupset#3]
I'm sorry for not providing an example dataset, but I'm trying to plot the intersections of three sets (A, B, C). I think `ggupset` could easily plot the individual overlapping sets (A only, B only, C only, A&B, B&C, A&C, A&B&C) -- this plot would be similar to the output from UpSetR. However, would it be possible to also (or instead) plot the combined (aggregated) sets? For example, could I use `ggupset` to plot the total number of items in both A&B and A&B&C combined (i.e. the yellow area)? 

I understand that `ggupset` can use a column of lists (describing the set membership). If I understand correctly, would I simply mutate my data frame to include these additional "set types"? For example, the items in yellow would contain a list like this: `c("A", "B", "AB")` and/or `c("A", "B", "C", "AB", "AC", "BC")`? 

![Screen Shot 2019-05-07 at 11 18 40 AM](https://user-images.githubusercontent.com/7346750/57315764-dec19500-70b9-11e9-98aa-c0673a3a38d2.png)

**Comment by const-ae** [comment]
Hi Todd,

I am not sure I fully understand what you have in mind (as you said, code is always useful ;) ).

If you want to create the [power set](https://en.wikipedia.org/wiki/Power_set#Example) of the simple membership, you can use a function like this:

``` r
make_all_combinations <- function(set){
  unlist(lapply(seq_along(set), function(size){
    apply(combn(set, size), 2, paste0, collapse="-")
  }))
}
make_all_combinations(c("A", "C"))
#> [1] "A"   "C"   "A-C"
make_all_combinations(c("A", "B", "C"))
#> [1] "A"     "B"     "C"     "A-B"   "A-C"   "B-C"   "A-B-C"
```

<sup>Created on 2019-05-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>


Of course, in the next step you could go ahead and make a bar (or whatever) plot of that power set.

``` r
library(tidyverse)
library(ggupset)

df <- tribble(
  ~ id, ~ group,
  1,     "A",
  1,     "B",
  2,     "A",
  2,     "C",
  3,     "A",
  3,     "B",
  3,     "C",
  4,     "A",
  5,     "C",
)

simple_groups_df <- df %>%
  group_by(id) %>%
  summarize(groups = list(group))

simple_groups_df
#> # A tibble: 5 x 2
#>      id groups   
#>   <dbl> <list>   
#> 1     1 <chr [2]>
#> 2     2 <chr [2]>
#> 3     3 <chr [3]>
#> 4     4 <chr [1]>
#> 5     5 <chr [1]>

extended_groups_df <- simple_groups_df %>%
  mutate(groups = lapply(groups, make_all_combinations)) %>%
  unnest()

extended_groups_df
#> # A tibble: 15 x 2
#>       id groups
#>    <dbl> <chr> 
#>  1     1 A     
#>  2     1 B     
#>  3     1 A-B   
#>  4     2 A     
#>  5     2 C     
#>  6     2 A-C   
#>  7     3 A     
#>  8     3 B     
#>  9     3 C     
#> 10     3 A-B   
#> 11     3 A-C   
#> 12     3 B-C   
#> 13     3 A-B-C 
#> 14     4 A     
#> 15     5 C

ggplot(extended_groups_df, aes(x=groups)) +
  geom_bar() +
  axis_combmatrix(sep = "-")
```

![](https://i.imgur.com/8veWT1I.png)

<sup>Created on 2019-05-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I hope this is somewhat helpful. If not, I think actually some code or at least a sketch how the resulting plot should look, would be helpful.

**Comment by toddknutson** [comment]
Awesome! You read my mind. This is exactly what I was looking for. Thanks a lot!!

**Comment by const-ae** [comment]
Great, I am glad I could help. I will then close this issue now.
