### ISSUE TITLE
showing percent instead of counts 

### ISSUE THREAD

**Issue by zawkzaw** [const-ae/ggupset#35]
Hello

If I want to show percent bars with labels of  percent for each bar, how can I do it. I don't find any argument for ggupset for that functionality.     

Thanks

Ko Ko Zaw

**Comment by const-ae** [comment]
Hi Ko Ko Zaw,

one of the advantages of `ggupset` is that it is modular and plays nicely with the existing functionality of `ggplot2`. This means that you can add a `geom_text()` layer to your plot and display arbitrary information. For more details see for example this blog post https://finnstats.com/index.php/2021/09/10/adding-text-labels-to-ggplot2-bar-chart/

Best,
Constantin

**Comment by zawkzaw** [comment]
Hello Constantin,

Thank for your quick reply.

Under  of your demonstration  of "Adding Numbers on top", the following codes produce the graph  with counts and bars ordered by frequency.  

**tidy_movies %>%
  distinct(title, year, length, .keep_all=TRUE) %>%
  ggplot(aes(x=Genres)) +
    geom_bar() +
    geom_text(stat='count', aes(label=after_stat(count)), vjust=-1) +
    scale_x_upset(n_intersections = 20) +
    scale_y_continuous(breaks = NULL, lim = c(0, 1350), name = "")**

May I request you to show how to modify these  codes to produce he graph with percents  and bars ordered by percent?
In fact, I tried different ways but failed.  

Thanks in advance.

Ko Ko Zaw
