### ISSUE TITLE
Implementation of modes

### ISSUE THREAD

**Issue by KerstenBreuer** [const-ae/ggupset#7]
Hi Consti,

thanks a lot for this convenient package. It would be super cool if you could implement modes like in the ComplexHeatmap package (Chapter 8.2):
https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html

I have a use case in which I am not interested in the distinct overlap but the intersection.

Thanks a lot,
Kersten

**Comment by const-ae** [comment]
Hi Kersten,

could you maybe say a little bit more about your use case, so I have a better idea what you are trying to achieve?

Can you achieve the intersection by using [list-columns](https://github.com/const-ae/ggupset#what-if-i-need-more-flexibility) to just do the filtering yourself?

Best, Constantin

**Comment by KerstenBreuer** [comment]
Yes, issue #3 is pretty much what I wanted.

Thanks :)

**Comment by const-ae** [comment]
Great, I will close this issue then.
If something else comes up, feel free to re-open :)
